name: Run Job Scraper Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *"  # This runs the script every 2 hours (UTC)
  workflow_dispatch:

jobs:
  run-job-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js version 18

      - name: Install dependencies
        run: npm install

      - name: Run the job scraper script
        run: node index.js

      - name: Commit and push CSV files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout -b update-csv-files
          git add jobs_remoterocketship.csv jobs_smartrecruiters.csv
          git commit -m "Update job openings CSV files [skip ci]" || echo "No changes to commit"
          git push origin update-csv-files
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-csv-files
          base: main
          title: "Update job openings CSV files"
          body: "Automated update of CSV files."

