name: Run Job Scraper Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *"  # This runs the script every 2 hours (UTC)
  workflow_dispatch:

jobs:
  run-job-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js version 18

      - name: Install dependencies
        run: npm install

      - name: Run the job scraper script
        run: node index.js

      - name: Commit and push CSV files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main  # Fetch latest changes from the remote repository
          git checkout -b update-csv-files
          git pull origin main --rebase  # Pull latest changes from remote and rebase
          git add jobs_remoterocketship.csv jobs_smartrecruiters.csv
          git commit -m "Update job openings CSV files [skip ci]" || echo "No changes to commit"
          git push origin update-csv-files  # Push to remote branch

      - name: Upload jobs_remoterocketship.csv
        uses: actions/upload-artifact@v3
        with:
          name: jobs_remoterocketship
          path: jobs_remoterocketship.csv

      - name: Upload jobs_smartrecruiters.csv
        uses: actions/upload-artifact@v3
        with:
          name: jobs_smartrecruiters
          path: jobs_smartrecruiters.csv
